package config

import "github.com/BossRighteous/MiSTer_Games_Data_Utils/pkg/mister"

type DataConfig struct {
	ScrapeFolder string
	RdbName      string
	Systems      []mister.System
}

var DataConfigs map[string]DataConfig = map[string]DataConfig{
	"ATARI5200":       {ScrapeFolder: "ATARI5200", RdbName: "Atari - 5200.rdb", Systems: []mister.System{mister.Systems["Atari5200"]}},
	"ATARI7800":       {ScrapeFolder: "ATARI7800", RdbName: "Atari - 7800.rdb", Systems: mister.CoreGroups["Atari7800"]},
	"ATARI800":        {ScrapeFolder: "ATARI800", RdbName: "Atari - 8-bit.rdb", Systems: []mister.System{mister.Systems["Atari800"]}},
	"AVision":         {ScrapeFolder: "AVision", RdbName: "Entex - Adventure Vision.rdb", Systems: []mister.System{mister.Systems["AdventureVision"]}},
	"Amiga":           {ScrapeFolder: "Amiga", RdbName: "Commodore - Amiga.rdb", Systems: []mister.System{mister.Systems["Amiga"]}},
	"Amstrad":         {ScrapeFolder: "Amstrad", RdbName: "Amstrad - CPC.rdb", Systems: []mister.System{mister.Systems["Amstrad"]}},
	"Arcadia":         {ScrapeFolder: "Arcadia", RdbName: "Emerson - Arcadia 2001.rdb", Systems: []mister.System{mister.Systems["Arcadia"]}},
	"Atari2600":       {ScrapeFolder: "Atari2600", RdbName: "Atari - 2600.rdb", Systems: []mister.System{mister.Systems["Atari2600"]}},
	"AtariLynx":       {ScrapeFolder: "AtariLynx", RdbName: "Atari - Lynx.rdb", Systems: []mister.System{mister.Systems["AtariLynx"]}},
	"C64":             {ScrapeFolder: "C64", RdbName: "Commodore - 64.rdb", Systems: []mister.System{mister.Systems["C64"]}},
	"Casio_PV-1000":   {ScrapeFolder: "Casio_PV-1000", RdbName: "Casio - PV-1000.rdb", Systems: []mister.System{mister.Systems["CasioPV1000"]}},
	"ChannelF":        {ScrapeFolder: "ChannelF", RdbName: "Fairchild - Channel F.rdb", Systems: []mister.System{mister.Systems["ChannelF"]}},
	"Coleco":          {ScrapeFolder: "Coleco", RdbName: "Coleco - ColecoVision.rdb", Systems: mister.CoreGroups["Coleco"]},
	"CreatiVision":    {ScrapeFolder: "CreatiVision", RdbName: "VTech - CreatiVision.rdb", Systems: []mister.System{mister.Systems["CreatiVision"]}},
	"GAMEBOY":         {ScrapeFolder: "GAMEBOY", RdbName: "Nintendo - Game Boy.rdb", Systems: mister.CoreGroups["Gameboy"]},
	"GBA":             {ScrapeFolder: "GBA", RdbName: "Nintendo - Game Boy Advance.rdb", Systems: []mister.System{mister.Systems["GBA"]}},
	"GBC":             {ScrapeFolder: "GBC", RdbName: "Nintendo - Game Boy Color.rdb", Systems: []mister.System{mister.Systems["GameboyColor"]}},
	"GameGear":        {ScrapeFolder: "GameGear", RdbName: "Sega - Game Gear.rdb", Systems: []mister.System{mister.Systems["GameGear"]}},
	"Genesis":         {ScrapeFolder: "Genesis", RdbName: "Sega - Mega Drive - Genesis.rdb", Systems: []mister.System{mister.Systems["Genesis"]}},
	"Intellivision":   {ScrapeFolder: "Intellivision", RdbName: "Mattel - Intellivision.rdb", Systems: []mister.System{mister.Systems["Intellivision"]}},
	"MSX":             {ScrapeFolder: "MSX", RdbName: "Microsoft - MSX.rdb", Systems: []mister.System{mister.Systems["MSX"]}},
	"MegaCD":          {ScrapeFolder: "MegaCD", RdbName: "Sega - Mega-CD - Sega CD.rdb", Systems: []mister.System{mister.Systems["MegaCD"]}},
	"N64":             {ScrapeFolder: "N64", RdbName: "Nintendo - Nintendo 64.rdb", Systems: []mister.System{mister.Systems["Nintendo64"]}},
	"NEOGEO":          {ScrapeFolder: "NEOGEO", RdbName: "SNK - Neo Geo.rdb", Systems: []mister.System{mister.Systems["NeoGeo"]}},
	"NES":             {ScrapeFolder: "NES", RdbName: "Nintendo - Nintendo Entertainment System.rdb", Systems: mister.CoreGroups["NES"]},
	"ODYSSEY2":        {ScrapeFolder: "ODYSSEY2", RdbName: "Magnavox - Odyssey2.rdb", Systems: []mister.System{mister.Systems["Odyssey2"]}},
	"PET2001":         {ScrapeFolder: "PET2001", RdbName: "Commodore - PET.rdb", Systems: []mister.System{mister.Systems["PET2001"]}},
	"PSX":             {ScrapeFolder: "PSX", RdbName: "Sony - PlayStation.rdb", Systems: []mister.System{mister.Systems["PSX"]}},
	"S32X":            {ScrapeFolder: "S32X", RdbName: "Sega - 32X.rdb", Systems: []mister.System{mister.Systems["Sega32X"]}},
	"Saturn":          {ScrapeFolder: "Saturn", RdbName: "Sega - Saturn.rdb", Systems: []mister.System{mister.Systems["Saturn"]}},
	"SMS":             {ScrapeFolder: "SMS", RdbName: "Sega - Master System - Mark III.rdb", Systems: mister.CoreGroups["SMS"]},
	"SNES":            {ScrapeFolder: "SNES", RdbName: "Nintendo - Super Nintendo Entertainment System.rdb", Systems: mister.CoreGroups["SNES"]},
	"Spectrum":        {ScrapeFolder: "Spectrum", RdbName: "Sinclair - ZX Spectrum.rdb", Systems: []mister.System{mister.Systems["ZXSpectrum"]}},
	"SVI328":          {ScrapeFolder: "SVI328", RdbName: "Spectravideo - SVI-318 - SVI-328.rdb", Systems: []mister.System{mister.Systems["SVI328"]}},
	"SuperVision":     {ScrapeFolder: "SuperVision", RdbName: "Watara - Supervision.rdb", Systems: []mister.System{mister.Systems["SuperVision"]}},
	"TGFX16":          {ScrapeFolder: "TGFX16", RdbName: "NEC - PC Engine - TurboGrafx 16.rdb", Systems: mister.CoreGroups["TGFX16"]},
	"TGFX16-CD":       {ScrapeFolder: "TGFX16-CD", RdbName: "NEC - PC Engine CD - TurboGrafx-CD.rdb", Systems: []mister.System{mister.Systems["TurboGrafx16CD"]}},
	"VECTREX":         {ScrapeFolder: "VECTREX", RdbName: "GCE - Vectrex.rdb", Systems: []mister.System{mister.Systems["Vectrex"]}},
	"VIC20":           {ScrapeFolder: "VIC20", RdbName: "Commodore - VIC-20.rdb", Systems: []mister.System{mister.Systems["VIC20"]}},
	"WonderSwan":      {ScrapeFolder: "WonderSwan", RdbName: "Bandai - WonderSwan.rdb", Systems: []mister.System{mister.Systems["WonderSwan"]}},
	"WonderSwanColor": {ScrapeFolder: "WonderSwanColor", RdbName: "Bandai - WonderSwan Color.rdb", Systems: []mister.System{mister.Systems["WonderSwanColor"]}},
	"X68000":          {ScrapeFolder: "X68000", RdbName: "Sharp - X68000.rdb", Systems: []mister.System{mister.Systems["X68000"]}},
	"ZX81":            {ScrapeFolder: "ZX81", RdbName: "Sinclair - ZX 81.rdb", Systems: []mister.System{mister.Systems["ZX81"]}},

	// PROBLEM SCRAPING
	//"AO486": {MisterCoreFolder: "AO486", RdbName: "DOS.rdb"},

	// NO STRATEGY FOR COLLECTION REDUCTION, DO MANUAL ARCADE
	// Too many ROMs, hold "hbmame": {MisterCoreFolder: "hbmame", RdbName: "HBMAME.rdb"},
	// Too many ROMs, hold "mame":   {MisterCoreFolder: "mame", RdbName: "MAME.rdb"},

	// NO MGL SUPPORT
	//"PC8801": {MisterCoreFolder: "PC8801", RdbName: "NEC - PC-8001 - PC-8801.rdb"},
	//"AtariST": {ScrapeFolder: "AtariST", RdbName: "Atari - ST.rdb", Systems: []mister.System{mister.Systems[""]}},

	// NO RDB FOUND
	//"APOGEE": {MisterCoreFolder:"APOGEE", RdbName: ""},
	//"APPLE-I": {MisterCoreFolder:"APPLE-I", RdbName: ""},
	//"AQUARIUS": {MisterCoreFolder:"AQUARIUS", RdbName: ""},
	//"ARCHIE": {MisterCoreFolder:"ARCHIE", RdbName: ""},
	//"AY-3-8500": {MisterCoreFolder:"AY-3-8500", RdbName: ""},
	//"AcornAtom": {MisterCoreFolder:"AcornAtom", RdbName: ""},
	//"AcornElectron": {MisterCoreFolder:"AcornElectron", RdbName: ""},
	//"Adam": {MisterCoreFolder:"Adam", RdbName: ""},
	//"AliceMC10": {MisterCoreFolder:"AliceMC10", RdbName: ""},
	//"Altair8800": {MisterCoreFolder:"Altair8800", RdbName: ""},
	//"Amstrad PCW": {MisterCoreFolder:"Amstrad PCW", RdbName: ""},
	//"Apple-II": {MisterCoreFolder:"Apple-II", RdbName: ""},
	//"Astrocade": {MisterCoreFolder:"Astrocade", RdbName: ""},
	//"BBCBridgeCompanion": {MisterCoreFolder:"BBCBridgeCompanion", RdbName: ""},
	//"BBCMicro": {MisterCoreFolder:"BBCMicro", RdbName: ""},
	//"BK0011M": {MisterCoreFolder:"BK0011M", RdbName: ""},
	//"C128": {MisterCoreFolder:"C128", RdbName: ""},
	//"C16": {MisterCoreFolder:"C16", RdbName: ""},
	//"COCO3": {MisterCoreFolder:"COCO3", RdbName: ""},
	//"Casio_PV-2000": {MisterCoreFolder:"Casio_PV-2000", RdbName: ""},
	//"CoCo2": {MisterCoreFolder:"CoCo2", RdbName: ""},
	//"EDSAC": {MisterCoreFolder:"EDSAC", RdbName: ""},
	//"EpochGalaxyII": {MisterCoreFolder:"EpochGalaxyII", RdbName: ""},
	//"GAMEBOY2P": {MisterCoreFolder:"GAMEBOY2P", RdbName: ""},
	//"GBA2P": {MisterCoreFolder:"GBA2P", RdbName: ""},
	//"Galaksija": {MisterCoreFolder:"Galaksija", RdbName: ""},
	//"Gamate": {MisterCoreFolder:"Gamate", RdbName: ""},
	//"GameNWatch": {MisterCoreFolder:"GameNWatch", RdbName: ""},
	//"Homelab": {MisterCoreFolder:"Homelab", RdbName: ""},
	//"Interact": {MisterCoreFolder:"Interact", RdbName: ""},
	//"Jupiter": {MisterCoreFolder:"Jupiter", RdbName: ""},
	//"Laser": {MisterCoreFolder:"Laser", RdbName: ""},
	//"Lynx48": {MisterCoreFolder:"Lynx48", RdbName: ""},
	//"MACPLUS": {MisterCoreFolder:"MACPLUS", RdbName: ""},
	//"MEMTEST": {MisterCoreFolder:"MEMTEST", RdbName: ""},
	//"MegaDuck": {MisterCoreFolder:"MegaDuck", RdbName: ""},
	//"MultiComp": {MisterCoreFolder:"MultiComp", RdbName: ""},
	//"MyVision": {MisterCoreFolder:"MyVision", RdbName: ""},
	//"ORAO": {MisterCoreFolder:"ORAO", RdbName: ""},
	//"Ondra_SPO186": {MisterCoreFolder:"Ondra_SPO186", RdbName: ""},
	//"Oric": {MisterCoreFolder:"Oric", RdbName: ""},
	//"PCXT": {MisterCoreFolder:"PCXT", RdbName: ""},
	//"PDP1": {MisterCoreFolder:"PDP1", RdbName: ""},
	//"PMD85": {MisterCoreFolder:"PMD85", RdbName: ""},
	//"PocketChallengeV2": {MisterCoreFolder:"PocketChallengeV2", RdbName: ""},
	//"PokemonMini": {MisterCoreFolder:"PokemonMini", RdbName: ""},
	//"QL": {MisterCoreFolder:"QL", RdbName: ""},
	//"RX78": {MisterCoreFolder:"RX78", RdbName: ""},
	//"SAMCOUPE": {MisterCoreFolder:"SAMCOUPE", RdbName: ""},
	//"SGB": {MisterCoreFolder:"SGB", RdbName: ""},
	//"SPMX": {MisterCoreFolder:"SPMX", RdbName: ""},
	//"SharpMZ": {MisterCoreFolder:"SharpMZ", RdbName: ""},
	//"Sord M5": {MisterCoreFolder:"Sord M5", RdbName: ""},
	//"SuperVision8000": {MisterCoreFolder:"SuperVision8000", RdbName: ""},
	//"TI-99_4A": {MisterCoreFolder:"TI-99_4A", RdbName: ""},
	//"TRS-80": {MisterCoreFolder:"TRS-80", RdbName: ""},
	//"TSConf": {MisterCoreFolder:"TSConf", RdbName: ""},
	//"TatungEinstein": {MisterCoreFolder:"TatungEinstein", RdbName: ""},
	//"TomyScramble": {MisterCoreFolder:"TomyScramble", RdbName: ""},
	//"TomyTutor": {MisterCoreFolder:"TomyTutor", RdbName: ""},
	//"UK101": {MisterCoreFolder:"UK101", RdbName: ""},
	//"VC4000": {MisterCoreFolder:"VC4000", RdbName: ""},
	//"VECTOR06": {MisterCoreFolder:"VECTOR06", RdbName: ""},
	//"zx48": {MisterCoreFolder:"zx48", RdbName: ""},
	//"ZXNext": {MisterCoreFolder:"ZXNext", RdbName: ""},
	//"eg2000": {MisterCoreFolder:"eg2000", RdbName: ""},
}
